[2022-06-25 13:41:50,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-06-25T13:41:45.228075+00:00 [queued]>
[2022-06-25 13:41:50,995] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-06-25T13:41:45.228075+00:00 [queued]>
[2022-06-25 13:41:50,997] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-25 13:41:51,006] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-25 13:41:51,007] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-25 13:41:51,085] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-06-25 13:41:45.228075+00:00
[2022-06-25 13:41:51,099] {standard_task_runner.py:52} INFO - Started process 423 to run task
[2022-06-25 13:41:51,117] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2022-06-25T13:41:45.228075+00:00', '--job-id', '14', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpdigfr9oi', '--error-file', '/tmp/tmpbw2wclsn']
[2022-06-25 13:41:51,119] {standard_task_runner.py:80} INFO - Job 14: Subtask run_after_loop
[2022-06-25 13:41:51,315] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2022-06-25T13:41:45.228075+00:00 [running]> on host d075f8448180
[2022-06-25 13:41:51,540] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T13:41:45.228075+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-25T13:41:45.228075+00:00
[2022-06-25 13:41:51,545] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-25 13:41:51,546] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-06-25 13:41:51,563] {subprocess.py:85} INFO - Output:
[2022-06-25 13:41:51,568] {subprocess.py:92} INFO - 1
[2022-06-25 13:41:51,570] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-25 13:41:51,708] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220625T134145, start_date=20220625T134150, end_date=20220625T134151
[2022-06-25 13:41:51,810] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-25 13:41:51,898] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
